/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package MyTest

fun main() {
    val x = 4
    val y = 10
    println(y / x)
    println("Hello, world!\nMy name is Ahmed Siam!")
}
